version: '3'

networks:
  users-service:
    external: true

services:  
  api-gateway: 
    container_name: api-gateway
    hostname: api-gateway
    build: ./api-gateway
    env_file:
      - ./api-gateway/.env
    networks:
      - users-service
    depends_on:
      - users-service
    ports:
      - target: 3000
        published: 3000

  postgres_users-service: 
    container_name: postgres_users-service
    hostname: postgres_users-service
    image: postgres
    networks:
      - users-service
    env_file:
      - ./users-service/.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    restart: always
    ports: 
      - target: 5432
        published: 5432
        mode: host
    volumes:
      - pgdata:/var/lib/postgresql/data

  users-service:
    container_name: users-service
    hostname: users-service
    build: ./users-service
    command: npm run start:dev
    networks:
      - users-service 
    env_file:
      - ./users-service/.env
    volumes:
      - ./app/node_modules
    depends_on:
      - postgres_users-service
    ports: 
      - target: 8000
        published: 8000

volumes:
  pgdata:
